dist: xenial
language: csharp
solution: location/location.sln
script:
  - msbuild /p:Configuration=Release location/location.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./location/bin/Release/location.dll
  - msbuild /p:Configuration=Release location/locationserver.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./locationserver/bin/Release/locationserver.dll
