dist: bionic
language: csharp
dotnet: 2.2
mono: none
env:
  global:
  - path =
matrix:
  include:
    - solution: location/location.sln
    - solution: locationserver/locationserver.sln
script:
  - dotnet build location | $TRAVIS_SOLUTION
  - dotnet run --project $TRAVIS_SOLUTION
  - dotnet test --project $TRAVIS_SOLUTION
