dist: bionic
language: csharp
dotnet: 2.2
before_script:
  - chmod +x location/location.sln
  - chmod +x locationserver/locationserver.sln
matrix:
  include:
    - solution: location/location.sln
    - solution: locationserver/locationserver.sln
script:
  - dotnet build $TRAVIS_SOLUTION
  - dotnet run --project $TRAVIS_SOLUTION
  - dotnet test --project $TRAVIS_SOLUTION
