dist: bionic
language: csharp
dotnet: 2.2
mono: none
matrix:
  include:
    - solution: location/location.sln
    - solution: location/location.sln
script:
  - dotnet watch --verbose run
  - dotnet build
  - dotnet test
